sample_user = {'username': 'crushbone',
  'shipCount': 2, 
  'structureCount': 0, 
  'joinedAt': '2022-07-03T20:54:08.115Z', 
  'credits': 685213}

sample_flightplan = {
    'arrivesAt': '2021-03-28T23:11:50.068Z',
    'createdAt': '2021-03-28T23:05:05.078Z',
    'departure': 'OE-PM-TR',
    'destination': 'OE-CR',
    'distance': 46,
    'fuelConsumed': 13,
    'fuelRemaining': 67,
    'id': 'ckmtrssae0402zgopsy39y9z7',
    'shipId': 'ckmtrlqpz0109zgopkeqs4m5s',
    'terminatedAt': None,
    'timeRemainingInSeconds': 365 }

sample_location = {'symbol': 'OE-PM',
  'type': 'PLANET', 
  'name': 'Prime', 
  'x': -19, 
  'y': 3, 
  'allowsConstruction': False, 
  'traits': ['METAL_ORES', 'SOME_NATURAL_CHEMICALS'], 
  'dockedShips': 835}

sample_ship = {'id': 'cl55thau617774315s68iz3fpjj',
  'location': 'OE-NY', 
  'x': 43, 
  'y': -46, 
  'cargo': [{'good': 'FUEL', 'quantity': 14, 'totalVolume': 14}], 
  'spaceAvailable': 36, 
  'type': 'JW-MK-I', 
  'class': 'MK-I', 
  'maxCargo': 50, 
  'loadingSpeed': 25, 
  'speed': 1, 
  'manufacturer': 'Jackshaw', 
  'plating': 5, 
  'weapons': 5}

sample_system = {'symbol': 'OE', 'name': 'Omicron Eridani'}

# sample_market = [{'symbol': 'CONSTRUCTION_MATERIALS',
#   'volumePerUnit': 1,
#   'pricePerUnit': 140,
#   'spread': 4,
#   'purchasePricePerUnit': 144,
#   'sellPricePerUnit': 136,
#   'quantityAvailable': 10},
#  {'symbol': 'METALS',
#   'volumePerUnit': 1,
#   'pricePerUnit': 2,
#   'spread': 1,
#   'purchasePricePerUnit': 3,
#   'sellPricePerUnit': 1,
#   'quantityAvailable': 93752},
#  {'symbol': 'FUEL',
#   'volumePerUnit': 1,
#   'pricePerUnit': 2,
#   'spread': 1,
#   'purchasePricePerUnit': 3,
#   'sellPricePerUnit': 1,
#   'quantityAvailable': 87271},
#  {'symbol': 'FUSION_REACTORS',
#   'volumePerUnit': 6,
#   'pricePerUnit': 20400,
#   'spread': 196,
#   'purchasePricePerUnit': 20596,
#   'sellPricePerUnit': 20204,
#   'quantityAvailable': 0}]

sample_structure = {"active": True,
        "consumes": ["DRONES", "MACHINERY"],
        "id": "ckon8d0j400291vnzmgwahsyz",
        "inventory": [{"good": "MACHINERY",
            "quantity": 18},
            {"good": "DRONES",
            "quantity": 15},
            {"good": "FOOD",
            "quantity": 4
            }],
        "location": "OE-PM",
        "ownedBy": {"username": "testuser0"},
        "produces": ["FOOD"],
        "status": "Production running. Required inventory is available.",
        "type": "FARM"}


sample_market = {"goods":
  [{"symbol": "METALS",
  "volumePerUnit": 1, 
  "pricePerUnit": 2, 
  "spread": 1, 
  "purchasePricePerUnit": 3, 
  "sellPricePerUnit": 1, 
  "quantityAvailable": 93641}, 
  {"symbol": "NARCOTICS", 
  "volumePerUnit": 1, 
  "pricePerUnit": 115, 
  "spread": 5, 
  "purchasePricePerUnit": 120, 
  "sellPricePerUnit": 110, 
  "quantityAvailable": 13}, 
  {"symbol": "FOOD", 
  "volumePerUnit": 1, 
  "pricePerUnit": 35, 
  "spread": 1, 
  "purchasePricePerUnit": 36, 
  "sellPricePerUnit": 34, 
  "quantityAvailable": 9}, 
  {"symbol": "RARE_METALS", 
  "volumePerUnit": 1, 
  "pricePerUnit": 81, 
  "spread": 4, 
  "purchasePricePerUnit": 85, 
  "sellPricePerUnit": 77, 
  "quantityAvailable": 33410}, 
  {"symbol": "EXPLOSIVES", 
  "volumePerUnit": 1,
  "pricePerUnit": 92, 
  "spread": 2, 
  "purchasePricePerUnit": 94, 
  "sellPricePerUnit": 90, 
  "quantityAvailable": 9}, 
  {"symbol": "FUEL", 
  "volumePerUnit": 1, 
  "pricePerUnit": 33, 
  "spread": 1, 
  "purchasePricePerUnit": 34, 
  "sellPricePerUnit": 32, 
  "quantityAvailable": 19509}],
  "location_id": "OE-NY",
  "date": "2022-08-07 17:52:50.097518"}